/**
 * Production asset locations. The whole application is designed around these files; see docs/ASSET_SPEC.md and
 * TODO.md (generated by `npm run assets:check`) for exactly what each one must contain.
 */
export const KRISHNA_ASSETS = {
  bal: "/models/krishna/bal-krishna.glb",
  kishore: "/models/krishna/kishore-krishna.glb"
} as const;
export type KrishnaAssetKey = keyof typeof KRISHNA_ASSETS;

/** Decoders are copied from three's examples into public/decoders by scripts/copy-decoders.mjs and served locally. */
export const DECODER_PATHS = { draco: "/decoders/draco/", basis: "/decoders/basis/" } as const;

const probeCache = new Map<string, Promise<boolean>>();

/** Does a file exist at this URL? Cached, HEAD only, never throws. */
export function probeAsset(url: string): Promise<boolean> {
  let result = probeCache.get(url);
  if (!result) {
    result = fetch(url, { method: "HEAD", cache: "no-store" })
      .then((response) => response.ok)
      .catch(() => false);
    probeCache.set(url, result);
  }
  return result;
}
